# Generated by Django 5.2.6 on 2025-09-04 23:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Magrello', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartao',
            name='status',
            field=models.CharField(choices=[('pendente', 'Pendente'), ('andamento', 'Em andamento'), ('concluida', 'Concluída')], default='pendente', max_length=20),
        ),
    ]
